#!/usr/bin/env python3
# -*- coding:utf-8 -*-
# ================================================================================================ #
# Project    : AI-Enabled Voice of the Mobile Technology Customer                                  #
# Version    : 0.1.0                                                                               #
# Python     : 3.10.10                                                                             #
# Filename   : /aimobile/scraper/appstore/config/config_test.yml                                   #
# ------------------------------------------------------------------------------------------------ #
# Author     : John James                                                                          #
# Email      : john.james.ai.studio@gmail.com                                                      #
# URL        : https://github.com/john-james-ai/aimobile                                           #
# ------------------------------------------------------------------------------------------------ #
# Created    : Monday March 27th 2023 07:00:33 pm                                                  #
# Modified   : Monday April 17th 2023 04:08:11 am                                                  #
# ------------------------------------------------------------------------------------------------ #
# License    : MIT License                                                                         #
# Copyright  : (c) 2023 John James                                                                 #
# ================================================================================================ #

# ================================================================================================ #
#                                 APPSTORE SCRAPER MICROSERVICE CONFIG                             #
# ================================================================================================ #
# Retry object
retry:
  total_retries: 5
  backoff_factor: 2
  status_forcelist:
  - 104
  - 429
  - 500
  - 502
  - 503
  - 504
  allowed_methods:
  - HEAD
  - GET
  - POST
  - PUT
  - DELETE
  - OPTIONS
  - TRACE
  raise_on_redirect: True
  raise_on_status: True
# Timeout Adapter
timeout: 30
# Session object
session:
  retries: 3
  delay: (1,8,)








  # Database: SQLite for metadata; MySQL for Review Text
  # ---------------------------------------------------------------------------------------------- #
  database:
    sqlite: aimobile/scraper/appstore/envs/test/data/database.db
    mysql: appstore_test_db

  # Session object parameters. Controls HTTP methods.
  # ---------------------------------------------------------------------------------------------- #
  session:

    sessions: 3
    timeout: 30
    delay_min: 1
    delay_max: 8

  # AppStore AppData Scraper Config
  # ---------------------------------------------------------------------------------------------- #
    request:
      max_pages: 5
      page_limit: 10
      country: us
      lang: en-us

# AppStore