#!/usr/bin/env python3
# -*- coding:utf-8 -*-
# ================================================================================================ #
# Project    : AI-Enabled Voice of the Mobile Technology Customer                                  #
# Version    : 0.1.0                                                                               #
# Python     : 3.10.10                                                                             #
# Filename   : /config/web.yml                                                                     #
# ------------------------------------------------------------------------------------------------ #
# Author     : John James                                                                          #
# Email      : john.james.ai.studio@gmail.com                                                      #
# URL        : https://github.com/john-james-ai/aimobile                                           #
# ------------------------------------------------------------------------------------------------ #
# Created    : Thursday April 20th 2023 12:00:43 pm                                                #
# Modified   : Friday April 21st 2023 06:31:56 am                                                  #
# ------------------------------------------------------------------------------------------------ #
# License    : MIT License                                                                         #
# Copyright  : (c) 2023 John James                                                                 #
# ================================================================================================ #
# ------------------------------------------------------------------------------------------------ #
#                                        SERVICE CONFIG                                            #
# ------------------------------------------------------------------------------------------------ #
web:
  session:
    retry:                    # Request module TimeOut HTTP Adapter Config
      total_retries: 5
      backoff_factor: 2
      status_forcelist:
      - 104
      - 429
      - 500
      - 502
      - 503
      - 504
      allowed_methods:
      - HEAD
      - GET
      - POST
      - PUT
      - DELETE
      - OPTIONS
      - TRACE
      raise_on_redirect: True
      raise_on_status: True

    timeout: 30

    session_retries: 3        # An external retry loop in addition to the request retry
    delay_min: 1              # Minimum time for random delay between HTTP requests
    delay_max: 8              # Maximum time for random delay between HTTP requests